version: "3.9"
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: wer08
      POSTGRES_PASSWORD: M0rg0th&CO
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: backend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: wer08
      SPRING_DATASOURCE_PASSWORD: M0rg0th&CO
  
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 80:80

volumes:
  postgres-data:
